# .github/workflows/laravel-app-arm-build.yml
name: Build Laravel App ARM

on:
  workflow_dispatch: # Habilita botão "Run workflow" no GitHub

jobs:
  build-arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build for ARM
        uses: docker/build-push-action@v5
        with:
          context: ./laravel/php8-2-arm/app
          file: ./laravel/php8-2-arm/app/Dockerfile
          push: true
          platforms: linux/arm64
          tags: matoso30/laravel-app:8.2-arm
